In [200]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.Max_columns", None)

# scikit-learn Library
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from time import time
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [191]:
df = pd.read_csv(r"C:\Users\HP\Downloads\train.csv")

In [192]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [193]:
df.shape

(1460, 81)

## Data Cleaning

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [195]:
df.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [198]:
# percentage of missing value in each columns

missing_percent = df.isna().mean()*100
missing_percent[missing_percent > 0]

LotFrontage     17.739726
Alley           93.767123
MasVnrType      59.726027
MasVnrArea       0.547945
BsmtQual         2.534247
BsmtCond         2.534247
BsmtExposure     2.602740
BsmtFinType1     2.534247
BsmtFinType2     2.602740
Electrical       0.068493
FireplaceQu     47.260274
GarageType       5.547945
GarageYrBlt      5.547945
GarageFinish     5.547945
GarageQual       5.547945
GarageCond       5.547945
PoolQC          99.520548
Fence           80.753425
MiscFeature     96.301370
dtype: float64

In [199]:
corr_matrix = df.corr()
corr_matrix["SalePrice"].sort_values(ascending = False)

ValueError: could not convert string to float: 'RL'

In [ ]:
# Drop a missing column with missing value greater than 30
cols_to_drop = missing_percent[missing_percent > 30].index
cols_to_drop

In [ ]:
df.drop(columns =cols_to_drop, inplace = True )

In [ ]:
missing_percent = df.isna().mean()*100
missing_percent[missing_percent > 0]

In [ ]:
# Check for outliers in the data or missing values
sns.boxplot(df["MasVnrArea"])

plt.show()

In [ ]:
df.info()

In [ ]:
numerical_cols = df.select_dtypes(include = ["int64", "float64"]).columns.tolist()

numerical_cols

In [ ]:
for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

In [ ]:
missing_percent = df.isna().mean()*100
missing_percent[missing_percent > 0]

In [ ]:
categorical_cols = df.select_dtypes(include = ["object"]).columns.tolist()

categorical_cols

In [ ]:
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
missing_percent = df.isna().mean()*100
missing_percent[missing_percent > 0]

In [ ]:
df.head()

## Feature Encoding

In [ ]:
# y = mx + c the basic regression model

# x is the independent variable - features
# y is the dependent variable - target

In [ ]:
x = df.drop(columns = ["SalePrice","Id"])

y = df["SalePrice"]

In [ ]:
categorical_cols

## Label Encoder

In [ ]:
x_lab = x.copy()

In [ ]:
for col in categorical_cols:
    le = LabelEncoder() # Create an instance
    x_lab[col] = le.fit_transform(x_lab[col]) # Transform each categorical column

In [ ]:
x_lab.head()

In [ ]:
x.head()

## One Hot Encoder

In [ ]:
x_oh = x.copy()

In [ ]:
x_oh = pd.get_dummies(x_oh, columns = categorical_cols, dtype = int)

In [ ]:
x_oh.head()

In [ ]:
x_oh.shape

In [ ]:
x["MSZoning"].value_counts()

In [ ]:
x.head()

In [ ]:
x.shape

In [ ]:
x_oh.shape

## Feature Scaling

In [ ]:
x_lab.head()

In [ ]:
# Standard Scaler ( Mean = 0, std = 1)

scaler = StandardScaler()

scaledX = scaler.fit_transform(x_lab)

In [ ]:
scaledX

## Train-Test-Split

In [ ]:
# 80 : 20 ratio
X_train, X_test, y_train, y_test = train_test_split(scaledX, y, test_size =0.2,random_state = 7 )

In [ ]:
X_train.shape

In [ ]:
X_test.shape

## Training

## Evaluation metrics
- Mean Absolute Error(MAE): The average of the absolute differences between the actual and predicted values.
- Mean Squared Error (MSE): The average of the squared differences between the actual and predicted values.
- Root Mean Squared Error (RMSE): Square root of MSE
- R-squared score - coefficient of determination (0-1): It represents how well the model fits to the data.
- While evaluating your model, you strive to reduce errors, and increase R2 score

In [205]:
# Linear regress assumes there is linear relationship between X and y

linreg = LinearRegression() # Create an instance of the model
start = time()
linreg.fit(X_train, y_train)
end = time()
train_time = (end-start) * 1000
print('this model took {:,.2f} miliseconds to fit.' .format(train_time))

this model took 36.50 miliseconds to fit.

In [209]:
# Evaluate on the test set
def show_n_results(y_test, preds, n = 10):
    results = pd.DataFrame(y_test.iloc[:n])
    results.insert(1, 'price_pred', preds[:n].round(2))
    pd.options.display.float_format = '${:,.0f}'.format
    
    return results

In [210]:
show_n_results(y_test,linpreds)

      SalePrice  price_pred
606      152000    $155,765
1210     189000    $214,992
492      172785    $177,387
410       60000     $83,152
396      123000    $128,437
1115     318000    $306,813
1238     142500    $155,562
1150     124000    $131,277
1275     137000    $163,353
71       129500    $115,076

In [211]:
linpreds = linreg.predict(X_test)

linpreds

array([155764.65911765, 214992.46270485, 177386.76302838,  83152.11735419,
       128436.81331323, 306813.14490482, 155561.55417943, 131277.02557368,
       163352.65138925, 115075.49621134, 229964.90510034, 167703.02530739,
       118146.73497193, 202110.89592327, 197352.54817997, 200332.2666422 ,
       234437.40265347, 132213.56727212, 157043.63797149, 166100.85571278,
       191692.21640686, 162948.51286917, 101508.24436405, 240476.61247479,
       330968.7713947 , 157430.92226691, 104536.6761438 , 175336.09751299,
       236817.39245331, 120161.8425876 , 196762.34940887, 210607.73815499,
       270571.14549416, 251045.46129682, 192156.96907008, 275571.37068711,
       137207.75374108, 131728.08910693, 285009.08652196, 205147.12913029,
       121273.02841903, 187502.80561103, 157175.87201074, 146093.21268581,
       263223.01376869, 244895.6851061 , 192903.81973381, 186688.57416092,
       284925.68096507, 247849.21372248, 244441.99434784, 183271.66028458,
       171679.92869883, 216852.96085725, 111590.6738651 , 110193.55119178,
       307077.43621529, 162311.86868343, 222893.71956536, 202272.74959658,
       158211.76426974, 239401.15166887, 162814.57246111, 127333.57910675,
        99297.99338411, 213302.68415182, 113697.20622657, 178075.90847819,
       170391.78551838, 178115.75923269, 197898.90928118, 196858.84089449,
        97495.32882351, 143425.89365753, 363453.65030925, 324840.62922889,
       157546.57412736, 108415.79232112, 126120.20350564,  86711.60648669,
       133030.55592184, 335894.9337923 , 203183.3000421 , 340179.09674297,
       318069.94538116, 141502.39597548, 105190.07514597, 133278.30283008,
       368064.89642092,  70447.64080538, 339324.3912469 , 121338.09906258,
       406175.05899083, 135332.27387704, 109860.32924075, 208546.92512437,
       293725.51295946, 164443.47390417, 154587.27275786, 205645.85448467,
       139921.80727246, 132862.86860702, 238200.49160175, 209286.52751769,
        91314.13784697, 224507.5903861 , 121592.14785485, 298530.1792538 ,
       210175.22416982, 129970.7745448 ,  72098.87711897,  89594.38694406,
       209838.02096765, 231709.12707557, 239708.97077526, 167003.03894566,
       159079.85338727, 112516.76214306, 265669.06345957, 208217.38565512,
       106340.99246902, 211776.00564203, 249722.61843539, 115968.334004  ,
       228213.27342766, 303890.93635028, 192924.07016641, 406276.21016067,
       190281.62880351, 130775.18773525, 161665.41317948, 144193.87237743,
       130088.14012665, 108902.53803849, 260564.35174354, 227563.46199771,
       255147.6995679 , 153664.27379886, 212193.0300877 , 111895.05153454,
       126766.44428676, 240229.40937155, 109682.60452608, 297167.40297974,
       279170.91786372, 380743.82729699, 104013.40100457, 308320.54395262,
       290811.19752129,  77756.35499673, 162272.97346875, 255819.50885906,
       121993.97739255, 143168.1710076 , 235607.81400417, 108462.80217531,
       162850.21227042, 211254.68548967, 301064.25739225, 116980.29706869,
       218280.07068409, 154139.82505841, 373895.73346553, 223543.87996924,
       345363.15730142, 290957.39240148, 113477.84764433, 160850.57399823,
       169904.46283151, 158355.34606017, 111097.25891608, 137800.42128778,
       293564.75665764, 193578.53804874, 255871.40757908, 316962.80848778,
       164314.42508013, 200417.98012531,  66060.27328215, 169619.30067158,
       108623.99579695, 182451.33705997, 146342.50406972, 137989.13731919,
       219938.97522963, 124238.71685865, 215994.76492269, 236432.91770259,
       138974.71502221, 236321.01094084,  85022.1882431 , 134979.76445197,
       153427.47685139, 238578.25871692, 142372.41763308, 197257.33853082,
        91564.97025825, 119840.73471762, 258817.64510463, 102219.28977633,
       344516.10302068, 155578.43989514, 261403.13983975, 176989.78069188,
       180715.97570363, 183549.13978984, 125472.3112141 , 155612.66864302,
        94572.10607376, 297115.1603925 , 275014.91666279, 201715.93683295,
       189449.79284024, 156415.74741854, 188333.98513985, 103944.04316877,
       197775.85415355, 138844.75256154, 125523.02130962, 121705.10398794,
       204078.30191313, 107812.43457842, 138091.75678159,  72315.03053482,
        98350.43531298, 111604.62569853, 159634.25924777, 227912.05356372,
       147545.25729967, 135334.11260893,  94619.29332201, 183417.27268168,
       205134.57877555, 161036.19424078, 122199.53107175,  95424.60658822,
        74159.34611636, 312569.66715447, 112992.48175362,  76125.53184205,
       170419.33607997, 143671.53835055, 106918.31343982, 198387.60033867,
       292995.33855331, 121639.11248126, 177800.59127633, 159068.16777531,
       274011.67218228, 127812.36190244, 284490.27357739, 201540.6130806 ,
       282967.73036749, 126433.51291734, 222198.50375804,  81237.52661128,
        92731.46222655, 262502.0561956 ,  57823.54402367, 272749.65756821,
       125925.67628474, 166233.40484669,  58136.12383021, 314445.72660171,
       145078.36926383, 153459.69853221,  83163.64024845, 142606.98801785,
       120461.17194432, 182911.33927249, 156329.58399721, 161760.78274432,
       321234.30569499, 188068.4241802 , 128319.12201849, 506774.37852868,
       220653.9770256 , 228466.4869658 , 248636.76742157, 164544.5805927 ,
       187452.85841087, 124228.48210911, 119256.96186635,  75558.41378793,
       193702.05330306, 225201.29043853, 165363.73520492,  88337.73358393,
       118084.16658845, 168925.34554788, 147569.64973867, 249252.29321364])

In [212]:
# r2_score

r2_score(y_test, linpreds)

0.8688062683836317

In [213]:
# MAE

mean_absolute_error(y_test, linpreds)

20147.755229475704

In [214]:
# MSE

mean_squared_error(y_test, linpreds)

948823276.9748857

In [215]:
# RMSE

np.sqrt(mean_squared_error(y_test, linpreds))

np.float64(30802.97513187461)

In [216]:
# Tree-base model : not affected by outliers and do not assume linear relationship

tree_reg = DecisionTreeRegressor()

tree_reg.fit(X_train, y_train)

DecisionTreeRegressor()

In [217]:
tree_preds = tree_reg.predict(X_test)

In [218]:
r2_score(y_test, tree_preds)

0.7555335448164138

In [219]:
mean_squared_error(y_test, tree_preds)

1768037697.0753424

In [220]:
mean_absolute_error(y_test, tree_preds)

27686.35616438356

In [221]:
np.sqrt(mean_squared_error(y_test, tree_preds))

np.float64(42048.04034762313)

In [222]:
# Random Forest : Ensemble

forest_reg = RandomForestRegressor()
forest_reg.fit(X_train, y_train)

RandomForestRegressor()

In [223]:
forest_preds = forest_reg.predict(X_test)

In [224]:
r2_score(y_test, forest_preds)

0.908596078606098

In [225]:
mean_absolute_error(y_test, forest_preds)

16950.184657534246

In [226]:
mean_squared_error(y_test, forest_preds)

661054207.0631719

In [227]:
np.sqrt(mean_squared_error(y_test, forest_preds))

np.float64(25710.974447950663)